// app/layout.tsx
import { Toaster } from "sonner"; 
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ConvexClientProvider from "@/components/providers/convex-provider"
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/components/providers/modal-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata: Metadata = {
  title: "Jotion",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/logo.svg",
        href: "/logo.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/logo-dark.svg",
        href: "/logo-dark.svg",
      },
    ],
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
          <ClerkProvider >
            <ConvexClientProvider>
              <EdgeStoreProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system" 
                  enableSystem
                  disableTransitionOnChange
                  storageKey="jotion-theme-2"
                >
                  <Toaster position="bottom-center"/>
                  <ModalProvider />
                    {children}
                </ThemeProvider>
              </EdgeStoreProvider>
            </ConvexClientProvider>
          </ClerkProvider>
      </body>
    </html>
  );
}